services:

  prometheus:
    image: prom/prometheus

    container_name: prometheus

    restart: unless-stopped

    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"

    networks:
      - backend

  grafana:
    image: grafana/grafana

    container_name: grafana

    restart: unless-stopped

    env_file:
      - ../.env

    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_password

    secrets:
      - grafana_password

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana

    networks:
      - backend

volumes:
  grafana-data:

secrets:
  grafana_password:
    file: ../secrets/grafana_password.txt

networks:
  backend:
    external: true
