name: Lint

on:
  push:
  pull_request:

jobs:

  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate compose
        run: |
          docker compose -f compose/docker-compose.yml config

  hadolint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/keycloak/Dockerfile
