name: Security

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * 1"

jobs:

  trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .

  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Detect secrets
        uses: gitleaks/gitleaks-action@v2
